#!/usr/bin/env bash
# A Bash script that configures a new Ubuntu machine
# with NginX (this script will be run on the server itself)

# Update package lists
sudo apt-get -y update

# Install nginx
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.html

# Create a custom Nginx configuration file for redirection
sudo echo "
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location /redirect_me {
        return 301 http://example.com/new_page;
    }

    root /var/www/html;
    index index.html index.htm;

    location / {
        try_files \$uri \$uri/ =404;
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart nginx
sudo service nginx restart
