#!/usr/bin/env bash
# Update the package list and install Load Balancer

sudo apt-get update -y
sudo apt-get install -y haproxy

# Configure HAProxy
cat <<EOL | sudo tee /etc/haproxy/haproxy.cfg
frontend web
    bind 0.0.0.0:80
    mode http
    default_backend app_servers

backend app_servers
    mode http
    balance roundrobin
    server 165654-web-01 54.236.232.78:80 check
    server 165654-web-02 3.90.83.202:80 check
EOL

# Ensure HAProxy can be managed via an init script then restart
sudo systemctl enable haproxy
sudo systemctl restart haproxy
