#!/usr/bin/env bash
#Bash script that configures the container so that Nginx is running as the nginx user
sudo pkill -o apache2
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo chown -R nginx:nginx /etc/nginx/ /var/log/nginx/
sudo chmod 777 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
